version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: order
      POSTGRES_DB: orderflow
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    ports:
      - "5044:5044"
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://order:example@db:5432/orderflow?sslmode=disable
      REDIS_ADDR: redis:6379
    ports:
      - "8443:8443"
