basePath: /
definitions:
  main.loginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  order.Order:
    properties:
      id:
        type: string
      item:
        type: string
      quantity:
        type: integer
    type: object
host: localhost:8443
info:
  contact: {}
  description: API for managing orders
  title: OrderFlow API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates user and sets session cookie
      parameters:
      - description: Credentials
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/main.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Login
  /orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/order.Order'
            type: array
      security:
      - ApiKeyAuth: []
      summary: List orders
    post:
      consumes:
      - application/json
      parameters:
      - description: Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/order.Order'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/order.Order'
      security:
      - ApiKeyAuth: []
      summary: Create order
  /orders/{id}:
    delete:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      security:
      - ApiKeyAuth: []
      summary: Delete order
    get:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.Order'
      security:
      - ApiKeyAuth: []
      summary: Get order
    put:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      - description: Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/order.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.Order'
      security:
      - ApiKeyAuth: []
      summary: Update order
swagger: "2.0"
